org.gradle.jvmargs=-Xmx6144m -Dfile.encoding=UTF-8 -XX:-UseOnStackReplacement
kotlin.native.jvmArgs=-Xmx6g
android.useAndroidX=true
kotlin.code.style=official
phoebe.versionName=2026.0704.1835
phoebe.versionCode=382
# use -Pphoebe.desktopProguard=true to enable.
phoebe.desktopProguard=false
phoebe.events.backendUrl=https://phoebe-xi.vercel.app